# Behaviorbot config. See https://github.com/behaviorbot/ for more information.

# Configuration for update-docs - https://github.com/behaviorbot/update-docs
updateDocsComment: "Thanks for the pull request! If you are making any changes to the user-facing functionality, please be sure to update the documentation in the `README` or `docs/` folder alongside your change. :heart:"

# Configuration for request-info - https://github.com/behaviorbot/request-info
requestInfoReplyComment: Thanks for this. Do you mind providing a bit more information about what problem you're trying to solve?
requestInfoLabelToAdd: more-information-needed

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
#newIssueWelcomeComment: >
#  Welcome!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
newPRWelcomeComment: Welcome! Congrats on your first pull request to The Hacker Cookbook. If you haven't already, please be sure to check out [the contributing guidelines](https://github.com/hotpeppersec/1337-Noms-The-Hacker-Cookbook/blob/master/docs/CONTRIBUTING.md).

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
firstPRMergeComment: "Congrats on getting your first pull request to The Hacker Cookbook merged! You rock! :tada:<br /><br />If you're interested in tackling another bug or feature, take a look at [the open issues](https://github.com/hotpeppersec/1337-Noms-The-Hacker-Cookbook/issues)."
